apiVersion: v1
kind: Service
metadata:
  name: {{ include "xyzchart.fullname" . }}
  labels:
    {{- include "xyzchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: endpoint
  selector:
    {{- include "xyzchart.selectorLabels" . | nindent 4 }}
