name: 'Deploy to ACR'

on:
  push:
    branches: [ "main" ]
    paths: 
    - "**.js"
    - "**.json"
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.6.0]

    steps:
    - uses: actions/checkout@v3
    - name: NPM Build and Test
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: xyzacrliatrio.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Image  
      run: |
        docker build . -t xyzacrliatrio.azurecr.io/xyzapp:${{ github.sha }}
        docker push xyzacrliatrio.azurecr.io/xyzapp:${{ github.sha }}
