name: 'Deploy to ACR'

on:
  push:
    branches: [ "main" ]
    paths: 
    - "**.js"
    - "**.json"
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.6.0]

    steps:
    - uses: actions/checkout@v3
    - name: NPM Build and Test
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    # Logs in with your Azure credentials
    - name: Azure Login
      uses: azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Container Registry Login
      uses: azure/docker-login@v1
      with:
        login-server: xyzacrliatrio.azurecr.io
    
    - name: Build and push image  
      run: |
        docker build . -t xyzacrliatrio.azurecr.io/xyzapp:${{ github.sha }}
        docker push xyzacrliatrio.azurecr.io/xyzapp:${{ github.sha }}
